name: ACI-WorkflowContainer-Stage
run-name: Deploying Version 0.0.0
on:
  pull_request:
    types: closed
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract Version from run-name
        id: extract_version
        run: |
          run_name="Deploying Version 0.0.0"
          version=$(echo "$run_name" | grep -oP '(?<=Version )\d+\.\d+\.\d+')
          echo "Extracted version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

  end:
    needs: extract_version
    runs-on: ubuntu-latest
    steps:
      - name: Print Extracted Version
        run: "echo 'Extracted Version: ${{ needs.extract_version.outputs.version }}'"

  label:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labeler.yml
