name: ACI-WorkflowContainer-Stage
run-name: Deploying Version 0.0.1
on:
  pull_request:
    types: closed
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract Version from run-name
        id: extract_version
        run: |
          run_name="Deploying Version 0.0.0"
          version=$(echo "$run_name" | grep -oP '(?<=Version )\d+\.\d+\.\d+')
          echo "Extracted version: $version"
          echo "version=$version" >>  $GITHUB_ENV

      - name: Create version.txt file
        run: echo "${{ env.version }}" > version.txt
        
      - name: Upload Version as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-v
          path: version.txt        
            


  
