name: ad-hoc-generic-workflow-prod-pipeline

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Git Commit ID'
        required: true
        type: string
      WorkflowName:
        description: 'Name of the Workflow'
        required: true
        type: string
      Run_id:
        description: 'Run ID'
        required: true
        type: string
      Build_id:
        description: 'Build ID'
        required: true
        type: string
      Artifact_Folder:
        description: 'Artifact Folder'
        required: true
        type: string
      Package_version:
        description: 'Package Version'
        required: true
        type: string

run-name: WFV_Python_1.0.${{inputs.Build_id}}-${{inputs.WorkflowName}}

jobs:
  Build_Img_PRD:
    uses: ./.github/workflows/ad-hoc-templates.yml
    with:
      commit_id: ${{ inputs.commit_id }}
      WorkflowName: ${{ inputs.WorkflowName }}
      Run_id: ${{ inputs.Run_id }}
      Build_id: ${{ inputs.Build_id }}
      Artifact_Folder: ${{ inputs.Artifact_Folder }}
      Package_version: ${{ inputs.Package_version }}
  

  Register_ROS_STAGE:
    if: ${{ github.ref == 'refs/heads/main' && inputs.WorkflowName == 'StepRateAnalysis' }}
    uses: ./.github/workflows/ad-hoc-templates.yml
    with:
      commit_id: ${{ inputs.commit_id }}
      WorkflowName: ${{ inputs.WorkflowName }}
      Run_id: ${{ inputs.Run_id }}
      Build_id: ${{ inputs.Build_id }}
      Artifact_Folder: ${{ inputs.Artifact_Folder }}
      Package_version: ${{ inputs.Package_version }}  
