name: Load Workflow Variables Dynamically

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
env:
  JSON_DATA: ${{ vars.WORKFLOW_VARIABLES_JSON }}

jobs:
  load-variables:
    runs-on: windows-latest

    steps:
      - name: Debug secret (encode)
        run: |
          echo "${{ secrets.ADMIN_PASSWORD }}" | base64
          echo "${{ secrets.ADMIN_ID }}" | base64
