name: WF-SnoSki-SWRE-Stage
on:
  workflow_run:
    workflows:
      - ACI-WorkflowContainer-Stage
    types:
      - completed

jobs:
  use_version:
    runs-on: ubuntu-latest
    steps:
      - name: Debug version output
        run: "echo 'Version from extract_version job: ${{ needs.extract_version.outputs.version }}'"

      - name: Use Version from ACI Workflow
        run: "echo 'Deploying Version: ${{ github.event.workflow_run.outputs.version }}'"
