name: WF-SnoSki-SWRE-Stage
on:
  workflow_run:
    workflows:
      - ACI-WorkflowContainer-Stage
    types:
      - completed

jobs:
  use_version:
    runs-on: ubuntu-latest
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v3
        with:
          name: version-artifact

      - name: Read version from artifact
        run: |
          version=$(cat version.txt)
          echo "Deploying Version: $version"

