name: WF-SnoSki-SWRE-Stage
on:
  workflow_run:
    workflows:
      - ACI-WorkflowContainer-Stage
    types:
      - completed

jobs:
  use_version:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
         
      - name: Download version artifact
        run: wget https://github.com/pratham-mesh/clubbing-versions-github-actions/actions/runs/12197223778/artifacts/2284213107
        #uses: actions/download-artifact@v4
        #with:
        #  name: version-artifact
         # path: ./downloads
          
      - name: Display downloaded file
        run: cat ./version.txt 
        
      - name: List Files in Current Directory
        run: ls -l 

      - name: List available artifacts
        run: ls ${{ github.workspace }}


      - name: Read version from artifact
        run: |
          cat version.txt
          echo 'Deploying Version: $version'    

