name: WF-SnoSki-SWRE-Stage
on:
  workflow_run:
    workflows:
      - ACI-WorkflowContainer-Stage
    types:
      - completed

jobs:
  use_version:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
         
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with: 
          name: version
          path: ./downloads
          github-token: ${{ github.token }}
          repository: ${{github.repository}}
          run-id: 12197527413
      - name: Display downloaded file
        run: cat ./downloads/version.txt 
        
      - name: List Files in Current Directory
        run: ls -l 

      - name: List available artifacts
        run: ls ${{ github.workspace }}


      - name: Read version from artifact
        run: |
          cat ./downloads/version.txt
          echo 'Deploying Version: $version'    

