name: WF-SnoSki-SWRE-Stage
on:
  repository_dispatch:
    types:
      - trigger-wf-snoski-swre

jobs:
  use_version:
    runs-on: ubuntu-latest
    steps:
      - name: Receive version from dispatch
        run: |
          version=${{ github.event.client_payload.version }}
          echo "Deploying Version: $version"
