name: WF-SnoSki-SWRE-Stage
on:
  workflow_run:
    workflows:
      - ACI-WorkflowContainer-Stage
    types:
      - completed

jobs:
  use_version:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
         
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version-artifact
          path: version.txt
          
      - name: List Files in Current Directory
        run: ls -l 

      - name: Read version from artifact
        run: |
          cat version.txt
          echo 'Deploying Version: $version'    

